language: node_js

node_js:
  - '0.10'
  - '0.12'

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - npm install
  - npm install istanbul coveralls

env:
  global:
  - secure: "n4G+ZVgsut506QhhGSDHAQR25v5mvOVo/lSHld4kmcHWwYkJ6o1Tt6j9MxJRI7ua+mZ4XoI4adORRV0Qf5hNpiYDt9psfQ3VR5+3Nz0MlyAmSYd5fYIgsnKtbxhsrINzYOVXEm/unGIQt3xXHN6UqiSh8Ghj2C7/pdFPIKl7W4Egt5wBf7+q8JckmNRZPWTHO2nti6nAcad/YrUUbrjpJO0ZXzPB30fKIXxHR2SbUihbSE+pHRRGqHztE6tIChJcZ2LQMdx1RGYhyeWLBnbBY4zukMBS3wYSUWD802OCmeypw4QZ+XpNRQYFNhiWkZpVZzCZUFnFHQojluTVPHk8zftE8zcnMhr2aZo3x7camB6QCButmCQ9RFatCCBtgtQyN6U5GT23gstQe7lhc/h/dw8mxf4LJHUlUuUPwreyVqKxkmvXtN1Epfyc8/YV7TjZlTgEB7cvAKmwTtKUPxDnAu019vHtTWPL+IqqAEH2Lh24DlDm6pJgcOhKiVbXp1ePuB5Pg0mSCl417alenrddyv263Fh0a1n4t/qvnXSAham25BEOOjz4xc/dbPzDp9Q7opYCZlkU/6j8u8hbqTLNBDEh8lgC5gYEFNu7qJvlkkMWEWviXlTQC+nmN/d/YnSpVC4DHN/geXpki9zU3miPRPe70p9CUprsqfG/j+94b2g="
